### SAVE USER
POST http://localhost:8080/players
Content-Type: application/json

{
  "name": "Cassiru",
  "email": "{{$random.email}}",
  "phone": "{{$random.uuid}}",
  "groupType": "JUSTICE_LEAGUE"
}